# Goal (Client requests a state transition)
int64 target_state_id
string target_state
int64 tran_signal  

---
# Result (Final outcome of the state transition)
bool success
float64 time_elapsed
string error_message


---
# Feedback (Ongoing updates during transition)
string current_state
float64 progress
